version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
      - emotion-api
    env_file:
      - ./backend/.env

  emotion-api:
    build: ./emotion-api
    ports:
      - "8000:8000"
    env_file:
      - ./emotion-api/.env

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d  # 初期SQL自動実行

volumes:
  postgres_data:
